DROP TABLE IF EXISTS bookcatalog;
CREATE TABLE bookcatalog (
'ID' INTEGER PRIMARY KEY NOT NULL,
'ISBN' TEXT,
'TITLE' TEXT,
'AUTHORS' TEXT,
'PAGECOUNT' INTEGER,
'AVERAGERATING' FLOAT,
'THUMBNAIL' TEXT
);